import { z } from "zod";
import { runQuery, saveAnswer } from "@vale/core";
import type { ToolDefinition, ValeMcpContext } from "./types.js";
import { ok, err } from "./types.js";

const inputSchema = {
  question: z.string().min(1).describe("The question to answer using the knowledge base"),
  save: z.boolean().default(false).describe("Save the AI-generated answer to wiki/answers/"),
};

export function makeRunQueryTool(_ctx: ValeMcpContext): ToolDefinition {
  return {
    name: "run_query",
    description:
      "Execute a structured query against the knowledge base. " +
      "Returns assembled context from the most relevant files. " +
      "The AI should use this context to synthesize an answer with [[wikilink]] citations.",
    inputSchema,
    async handler(input, ctx) {
      const { question, save } = input as { question: string; save?: boolean };
      try {
        const result = await runQuery(ctx.workspacePath, question);

        let output = `## Query Results for: "${question}"\n\n`;
        output += `**Context assembled from ${result.matches.length} matches:**\n\n`;
        output += result.context;

        let answerPath: string | undefined;
        if (save) {
          answerPath = await saveAnswer(
            ctx.workspacePath,
            question,
            "[Answer will be generated by the AI]",
          );
          output += `\n\n---\nAnswer will be saved to: ${answerPath}`;
        }

        return ok(output, {
          matches: result.matches,
          answerPath,
          contextLength: result.context.length,
        });
      } catch (e) {
        return err(`Query failed: ${(e as Error).message}`);
      }
    },
  };
}
